#!/usr/local/bin/Rscript
source("psqlConnet.R") #load library(RPostgreSQL) and connect to server, connection name "conn"
source("signature.R")

################
#   Matching   #
################

#For testing purpose, take_snippet() chooses a snippet of song from database and get its windows' signatures, 
#the windows have to be taken from a single song, return error otherwise.
take_snippet <- function(start = 370, end = 380, song_data){ 
  if(start > nrow(song_data) | end > nrow(song_data)){
    stop("wrong input")
  }
  else{
    if(any(diff(song_data[start:end, "song_id"]) != 0)){
      stop("windows are not from the same song")
    }
    if(end - start < 10){
      stop("Recording snippet isn't long enough, matcher requires at least 10 seconds of snippet, try again")
    }
  }
  snippet_data <- song_data[start:end, -grep("^(song_id|window)", colnames(song_data))]
  snippet_songid <- song_data[start, 1]
  return(list(snippet_data = snippet_data, snippet_songid = snippet_songid))
} 

#factor function of match_signature(): make sure (song id, window) pair exists in song_data, exclude unmatching indices 
generate_next_search_matrix <- function(match_index, search_matrix){ 
  nextWinInfo <- search_matrix[match_index, grep("^(song_id|window)", colnames(search_matrix))]
  nextWinInfo[,"window"] <- nextWinInfo[,"window"]+1
  nextWinInd <- match(data.frame(t(nextWinInfo)), data.frame(t(song_data[,grep("^(song_id|window)", colnames(song_data))]))) #check id-window pair exists in song_data
  nextWinInd <- nextWinInd[!is.na(nextWinInd)]
  return(nextWinInd)
} 

#matching function: take signatures of snippets, a threshold w, and the number of matches to be returned
match_signature <-
  function(snippet, threshold = 0.01, N = 2, song_data, search_matrix = song_data){
    # N is the number of matches allowed to return
    frequency_id <- c()
    for (i in 1:nrow(snippet)) {
      distance <- matrix(dist(rbind(snippet[i, ], search_matrix[, -grep("^(song_id|window)", colnames(search_matrix))]), 
                        method = "euclidean"))[1:nrow(search_matrix), 1]
          match_index <- which(distance <= threshold) #identify the indices where distance is less than threshold
          if (all(is.na(match_index))) {
            return(NULL)
          }
          frequency_id <-
            c(frequency_id, search_matrix[match_index, "song_id"])  #store song_id generated by each loop in order to count the number of time the song matches
          next_index <-
            generate_next_search_matrix(match_index, search_matrix) #if succeeding id-window pair exists in song database, return next index of window
          search_matrix <- song_data[next_index, ]
    }
  
  match_id <- as.numeric(noquote(names(sort(table(frequency_id), decreasing = TRUE))[1:N])) #the closest match will have highest frequency of song id
  match_id <- match_id[!is.na(match_id)]
  match_id_text <- paste(match_id, collapse = ",")
  psql_text <- paste("select * from song_info where song_id in (", match_id_text, ");", collapse = "")
  match_song <- dbGetQuery(conn, psql_text) #return song id, song name, artist, and release year of the song
  return(match_song)
}

## evaluation for matcher ##
#The error rate of match_signature() is affected by the threshold, length of snippet windows and number of matches allowed.
#The error rate will increase if threshold increases or snippet's window is not long enough
#The error rate will decrease if the number of matches allowed increases so the function can tolerate more missing matches while contain correct match

#Case 1 is considered as reference, comparing with other cases
#candidate_snippet <- take_snippet(start = 100, end = 200) #correct answer is song "Closer", song_id = 1
#match_signature(candidate_snippet$snippet_data, N = 2) #wrong match!
# song_id    song_name           singer song_year
# 1       3 Send My Love            Adele      2016
# 2       4     Starving Hailee Steinfeld      2015

#Case 2:
#match_signature(candidate_snippet$snippet_data, N = 4) #increase N, increase accuracy rate
# song_id            song_name           singer song_year
# 1       1               Closer The Chainsmokers      2016
# 2       3         Send My Love            Adele      2016
# 3       4             Starving Hailee Steinfeld      2015
# 4       6 We Dont Talk Anymore     Charlie Puth      2016

#Case 3:
# candidate_snippet <- take_snippet(start = 50, end = 200)  #increase length of snippet, increase accuracy rate
# match_signature(candidate_snippet$snippet_data, N = 2) 
# song_id song_name           singer song_year
# 1       1    Closer The Chainsmokers      2016

#Case 4:
# candidate_snippet <- take_snippet(start = 100, end = 200)
# match_signature(candidate_snippet$snippet_data, N = 2, threshold = 0.005)  #decrease threshold, increase accuracy rate
# song_id song_name           singer song_year
# 1       1    Closer The Chainsmokers      2016
# 2       4  Starving Hailee Steinfeld      2015


